name: 'CodeSee Map'
description: 'Generate a Dependency Map snapshot for CodeSee'
inputs:
  api_token:
    description: The CodeSee API Token for the user who owns the dependency map
    required: true
  webpack_config_path:
    description: The path relative to your repo root where your webpack config file is stored
    default: '__NULL__'
  support_typescript:
    description: Should tsconfig.json be honored when traversing dependencies
    default: false
outputs:
runs:
  using: 'node12'
  main: 'src/action.js'
